# Render configuration
services:
  - type: web
    name: genzshop-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: genzshop
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:5174,https://genzshopf.vercel.app,https://genzshopa.vercel.app
      - key: PORT
        value: 80
